let paises = [
	{ src: 'img/1.png', pais: 'Alemania', capital: 'Berlín' },
	{ src: 'img/2.png', pais: 'Andorra', capital: 'Andorra La Vieja' },
	{ src: 'img/3.png', pais: 'Argentina', capital: 'Buenos Aires' },
	{ src: 'img/4.png', pais: 'Armenia', capital: 'Ereván' },
	{ src: 'img/5.png', pais: 'Australia', capital: 'Canberra' },
	{ src: 'img/6.png', pais: 'Austria', capital: 'Viena' },
	{ src: 'img/7.png', pais: 'Bélgica', capital: 'Bruselas' },
	{ src: 'img/8.png', pais: 'Bolivia', capital: 'La Paz' },
	{
		src: 'img/9.png',
		pais: 'Boznia y Herzegovina',
		capital: 'Sarajevo',
	},
	{ src: 'img/10.png', pais: 'Brasil', capital: 'Brasilia' },
	{ src: 'img/11.png', pais: 'Bulgaria', capital: 'Sofía' },
	{ src: 'img/12.png', pais: 'Canadá', capital: 'Ottawa' },
	{ src: 'img/13.png', pais: 'Chile', capital: 'Santiago de Chile' },
	{ src: 'img/14.png', pais: 'China', capital: 'Pekín' },
	{ src: 'img/15.png', pais: 'Colombia', capital: 'Bogotá' },
	{ src: 'img/16.png', pais: 'Corea del Norte', capital: 'Pyongyang' },
	{ src: 'img/17.png', pais: 'Corea del Sur', capital: 'Seúl' },
	{ src: 'img/18.png', pais: 'Costa Rica', capital: 'San José' },
	{ src: 'img/19.png', pais: 'Croacia', capital: 'Zagreb' },
	{ src: 'img/20.png', pais: 'Cuba', capital: 'La Habana' },
	{ src: 'img/21.png', pais: 'Dinamarca', capital: 'Copenhague' },
	{ src: 'img/22.png', pais: 'Ecuador', capital: 'Quito' },
	{ src: 'img/23.png', pais: 'El Salvador', capital: 'San Salvador' },
	{ src: 'img/24.png', pais: 'Escocia', capital: 'Edimburgo' },
	{ src: 'img/25.png', pais: 'Eslovaquia', capital: 'Bratislava' },
	{ src: 'img/26.png', pais: 'Eslovenia', capital: 'Liubliana' },
	{ src: 'img/27.png', pais: 'España', capital: 'Madrid' },
	{
		src: 'img/28.png',
		pais: 'Estados Unidos',
		capital: 'Washington D.C.',
	},
	{ src: 'img/29.png', pais: 'Estonia', capital: 'Tallin' },
	{ src: 'img/30.png', pais: 'Finlandia', capital: 'Helsinki' },
	{ src: 'img/31.png', pais: 'Francia', capital: 'París' },
	{ src: 'img/32.png', pais: 'Gales', capital: 'Cardiff' },
	{ src: 'img/33.png', pais: 'Georgia', capital: 'Tiflis' },
	{ src: 'img/34.png', pais: 'Grecia', capital: 'Atenas' },
	{
		src: 'img/35.png',
		pais: 'Guatemala',
		capital: 'Ciudad de Guatemala',
	},
	{ src: 'img/36.png', pais: 'Honduras', capital: 'Tegucigalpa' },
	{ src: 'img/37.png', pais: 'Hungría', capital: 'Budapest' },
	{ src: 'img/38.png', pais: 'Indonesia', capital: 'Yakarta' },
	{ src: 'img/39.png', pais: 'Inglaterra', capital: 'Londres' },
	{ src: 'img/40.png', pais: 'Irlanda', capital: 'Dublín' },
	{ src: 'img/41.png', pais: 'Islandia', capital: 'Reikiavik' },
	{ src: 'img/42.png', pais: 'Israel', capital: 'Jerusalén' },
	{ src: 'img/43.png', pais: 'Italia', capital: 'Roma' },
	{ src: 'img/44.png', pais: 'Japón', capital: 'Tokio' },
	{ src: 'img/45.png', pais: 'Letonia', capital: 'Riga' },
	{ src: 'img/46.png', pais: 'Lituania', capital: 'Vilna' },
	{
		src: 'img/47.png',
		pais: 'Luxemburgo',
		capital: 'Ciudad de Luxemburgo',
	},
	{ src: 'img/48.png', pais: 'México', capital: 'Ciudad de México' },
	{ src: 'img/49.png', pais: 'Moldavia', capital: 'Chisináu' },
	{ src: 'img/50.png', pais: 'Nicaragua', capital: 'Managua' },
	{ src: 'img/51.png', pais: 'Noruega', capital: 'Oslo' },
	{ src: 'img/52.png', pais: 'Nueva Zelanda', capital: 'Wellington' },
	{ src: 'img/53.png', pais: 'Países Bajos', capital: 'Ámsterdam' },
	{ src: 'img/54.png', pais: 'Panamá', capital: 'Ciudad de Panamá' },
	{ src: 'img/55.png', pais: 'Paraguay', capital: 'Asunción' },
	{ src: 'img/56.png', pais: 'Perú', capital: 'Lima' },
	{ src: 'img/57.png', pais: 'Polonia', capital: 'Varsovia' },
	{ src: 'img/58.png', pais: 'Portugal', capital: 'Lisboa' },
	{ src: 'img/59.png', pais: 'Puerto Rico', capital: 'San Juan' },
	{ src: 'img/60.png', pais: 'Republica Checa', capital: 'Praga' },
	{ src: 'img/61.png', pais: 'Rumania', capital: 'Bucarest' },
	{ src: 'img/62.png', pais: 'Rusia', capital: 'Moscú' },
	{ src: 'img/63.png', pais: 'Serbia', capital: 'Belgrado' },
	{ src: 'img/64.png', pais: 'Suecia', capital: 'Estocolmo' },
	{ src: 'img/65.png', pais: 'Suiza', capital: 'Berna' },
	{ src: 'img/66.png', pais: 'Tailandia', capital: 'Bangkok' },
	{ src: 'img/67.png', pais: 'Turquía', capital: 'Ankara' },
	{ src: 'img/68.png', pais: 'Ucrania', capital: 'Kiev' },
	{ src: 'img/69.png', pais: 'Uruguay', capital: 'Montevideo' },
	{ src: 'img/70.png', pais: 'Venezuela', capital: 'Caracas' },
	{ src: 'img/71.png', pais: 'Vietnam', capital: 'Hanói' },
];
